# -*- coding: utf-8 -*-
"""Load the production runtime before main.py.

V238 keeps the proven V219 selfie UI/media flow and scene/hero generation,
but applies user photo #3 in an observable two-pass terminal face transfer.
Legacy Comet owners remain disabled. Text retouch keeps its original-preserving
local-mask guard and Telegram media requests use production timeouts.
"""

import contextlib
import os
import sys

from retouch_guard import guarded_openai_retouch

try:
    from neyrobot_prod.bootstrap import install_early
    install_early()
except Exception as exc:
    print(f"[neyrobot-prod] production bootstrap warning: {type(exc).__name__}: {exc}")

try:
    from neyrobot_prod.versioning import install_builder_hook as install_version_owner
    install_version_owner()
except Exception as exc:
    print(f"[neyrobot-prod] version owner warning: {type(exc).__name__}: {exc}")

try:
    from neyrobot_prod.celebrity_selfie import install_async as install_celebrity_selfie
    install_celebrity_selfie()
except Exception as exc:
    print(f"[neyrobot-prod] celebrity selfie warning: {type(exc).__name__}: {exc}")

try:
    from neyrobot_prod.selfie_commands_v206 import install_async as install_selfie_commands
    install_selfie_commands()
except Exception as exc:
    print(f"[neyrobot-prod] selfie commands warning: {type(exc).__name__}: {exc}")

try:
    from telegram.ext import ApplicationBuilder
    from neyrobot_prod import selfie_v219_triref_scene_owner as selfie_ui
    from neyrobot_prod import selfie_v229_canonical_two_stage as selfie_google
    from neyrobot_prod import selfie_v238_observable_double_transfer as selfie_terminal

    CANONICAL_SELFIE_VERSION = selfie_terminal.VERSION

    selfie_ui.patch_runtime()

    def _legacy_noop(*args, **kwargs):
        return True

    selfie_ui.patch_runtime = _legacy_noop
    selfie_ui.bind_runtime_apps = lambda *args, **kwargs: 0
    selfie_ui.install_builder_hook = _legacy_noop
    selfie_ui.install_async = lambda *args, **kwargs: None
    selfie_ui.install = lambda *args, **kwargs: None

    selfie_google.VERSION = CANONICAL_SELFIE_VERSION
    selfie_ui.VERSION = CANONICAL_SELFIE_VERSION

    async def _disabled_comet_route(*args, **kwargs):
        raise RuntimeError("Legacy Comet selfie route is disabled; use canonical terminal user transfer")

    def _force_canonical_aliases() -> None:
        selfie_ui.generate = selfie_terminal.generate
        selfie_ui.public_callback.__globals__["generate"] = selfie_terminal.generate
        selfie_ui._comet_generate = _disabled_comet_route
        with contextlib.suppress(Exception):
            selfie_ui.public_callback.__globals__["_comet_generate"] = _disabled_comet_route

    def _install_guarded_retouch() -> bool:
        runtime = sys.modules.get("__main__")
        if runtime is None or not hasattr(runtime, "_openai_image_edit_bytes"):
            return False

        async def _safe_retouch(img_bytes: bytes, user_instruction: str):
            return await guarded_openai_retouch(
                img_bytes,
                user_instruction,
                api_key=getattr(runtime, "OPENAI_IMAGE_KEY", ""),
                base_url=getattr(runtime, "IMAGES_BASE_URL", "https://api.openai.com/v1"),
                model=getattr(runtime, "IMAGES_MODEL", "gpt-image-1"),
                quality=getattr(runtime, "OPENAI_IMAGE_QUALITY", "medium"),
                timeout_s=float(os.environ.get("RETOUCH_TIMEOUT_S", "180") or "180"),
            )

        _safe_retouch.__name__ = "_openai_image_edit_bytes"
        _safe_retouch.__doc__ = (
            "Guarded local-mask retouch. Pixels outside the requested area are copied "
            "from the original image and cannot be regenerated by the provider."
        )
        runtime._openai_image_edit_bytes = _safe_retouch
        runtime.RETOUCH_PIPELINE_VERSION = "v233-local-mask-original-preserving-2026-08-04"
        print("[neyrobot-prod] guarded local-mask retouch installed", flush=True)
        return True

    _force_canonical_aliases()
    selfie_google.patch_runtime()
    _force_canonical_aliases()

    _builder_flag = "_neyrobot_v238_observable_double_transfer_builder_hooked"
    if not getattr(ApplicationBuilder, _builder_flag, False):
        _original_build = ApplicationBuilder.build

        def _build_with_canonical_selfie(self, *args, **kwargs):
            with contextlib.suppress(Exception):
                self.connect_timeout(float(os.environ.get("TELEGRAM_CONNECT_TIMEOUT_S", "30") or "30"))
                self.read_timeout(float(os.environ.get("TELEGRAM_READ_TIMEOUT_S", "90") or "90"))
                self.write_timeout(float(os.environ.get("TELEGRAM_WRITE_TIMEOUT_S", "90") or "90"))
                self.media_write_timeout(float(os.environ.get("TELEGRAM_MEDIA_WRITE_TIMEOUT_S", "180") or "180"))
                self.pool_timeout(float(os.environ.get("TELEGRAM_POOL_TIMEOUT_S", "30") or "30"))

            app = _original_build(self, *args, **kwargs)
            _install_guarded_retouch()
            selfie_google.bind_application(app)
            selfie_google.patch_runtime()
            _force_canonical_aliases()
            return app

        ApplicationBuilder.build = _build_with_canonical_selfie
        setattr(ApplicationBuilder, _builder_flag, True)

    selfie_google.install_async()
    _force_canonical_aliases()

    runtime = selfie_google._runtime()
    if runtime is not None:
        runtime.CELEBRITY_SELFIE_VERSION = CANONICAL_SELFIE_VERSION
        runtime.AI_SELFIE_RUNTIME_VERSION = CANONICAL_SELFIE_VERSION
        runtime.SELFIE_STORAGE_VERSION = CANONICAL_SELFIE_VERSION
        runtime.SELFIE_COMMANDS_VERSION = CANONICAL_SELFIE_VERSION
        runtime.SELFIE_ADMIN_VERSION = CANONICAL_SELFIE_VERSION
        runtime.CELEBRITY_SELFIE_ROUTE = "v238-scene-hero-body-then-double-photo3-terminal-transfer"
        runtime.AI_SELFIE_PROVIDER = "Google Gemini composition plus PiAPI two-pass terminal transfer"
        runtime.AI_SELFIE_ACTIVE_KEY_ENV = "GEMINI_IMAGE_API_KEY"
        runtime.AI_SELFIE_GENERATION_STAGES = 4
        runtime.AI_SELFIE_BODY_REFERENCES = 2
        runtime.AI_SELFIE_TERMINAL_FACE_REFERENCE = "photo_3_only_two_pass"
        runtime.AI_SELFIE_HERO_REFERENCES = 3
        runtime.AI_SELFIE_ALLOW_COMPOSITION_FALLBACK = False
        runtime.AI_SELFIE_TRACE_PREFIX = "AI_SELFIE_V238"

    print(f"[neyrobot-prod] V238 observable double terminal transfer owner installed version={CANONICAL_SELFIE_VERSION}", flush=True)
except Exception as exc:
    print(f"[neyrobot-prod] canonical selfie V238 warning: {type(exc).__name__}: {exc}")
